import type { NextFunction, Request, Response } from 'express';
import bcrypt from 'bcryptjs';
import { createHash, createHmac, randomBytes } from 'node:crypto';
import { Admin, Session, Worker, connectDatabase, validId } from './db';
import { AppError, text } from './errors';

export type Role = 'admin' | 'worker';
export type AuthSession = { role: Role; id: string };
export type AuthenticatedRequest = Request & { user: AuthSession };

function fail(res: Response, status: number, code: string, error: string) {
  return res.status(status).json({ code, error });
}

export function pinLookupSecret() {
  const value = process.env.PIN_LOOKUP_SECRET;
  if (!value || value.length < 24) {
    throw new AppError(500, 'PIN_LOOKUP_NOT_CONFIGURED', 'Worker PIN authentication is not configured.');
  }
  return value;
}

export function workerPinKey(pin: string) {
  return createHmac('sha256', pinLookupSecret())
    .update(`worktime-worker-pin:${pin}`)
    .digest('hex');
}

function sessionTokenHash(token: string) {
  return createHash('sha256').update(token).digest('hex');
}

export async function createSession(role: Role, accountId: string) {
  const token = randomBytes(32).toString('base64url');
  const expiresAt = new Date(Date.now() + (role === 'admin' ? 12 * 60 * 60 * 1000 : 30 * 24 * 60 * 60 * 1000));

  try {
    await Session.create({
      tokenHash: sessionTokenHash(token),
      role,
      accountId,
      expiresAt
    });
  } catch (error) {
    const mongoError = error as { code?: number };
    if (mongoError.code === 13) {
      throw new AppError(503, 'DATABASE_PERMISSION_DENIED', 'Database user does not have permission to write sessions.');
    }
    throw new AppError(503, 'SESSION_UNAVAILABLE', 'Unable to create a login session.');
  }

  return token;
}

export async function revokeSession(token: string) {
  if (!token) return;
  await Session.deleteOne({ tokenHash: sessionTokenHash(token) });
}

export async function loginAdmin(email: string, password: string) {
  const account = await Admin.findOne({ email, active: true }).select('+passwordHash');
  if (!account || typeof account.passwordHash !== 'string' || !account.passwordHash) return null;
  if (!(await bcrypt.compare(password, account.passwordHash))) return null;
  return account;
}

export async function findWorkerByPin(pin: string) {
  const pinKey = workerPinKey(pin);
  const direct = await Worker.findOne({ pinKey, active: true }).select('+pinHash +pinKey');

  if (direct && await bcrypt.compare(pin, direct.pinHash)) return direct;

  // Migration fallback for workers whose pinKey was generated by the previous auth system.
  const candidates = await Worker.find({ active: true }).select('+pinHash +pinKey');
  for (const worker of candidates) {
    if (await bcrypt.compare(pin, worker.pinHash)) {
      if (worker.pinKey !== pinKey) {
        worker.pinKey = pinKey;
        await worker.save();
      }
      return worker;
    }
  }

  return null;
}

export async function authenticate(req: Request, res: Response, next: NextFunction) {
  try {
    const header = text(req.headers.authorization);
    if (!header.startsWith('Bearer ')) {
      return fail(res, 401, 'AUTH_REQUIRED', 'Please sign in again.');
    }

    const token = header.slice(7);
    if (!token) return fail(res, 401, 'AUTH_REQUIRED', 'Please sign in again.');

    await connectDatabase();

    const session = await Session.findOne({
      tokenHash: sessionTokenHash(token),
      expiresAt: { $gt: new Date() }
    }).lean();

    if (!session || !validId(String(session.accountId))) {
      return fail(res, 401, 'AUTH_REQUIRED', 'Please sign in again.');
    }

    const activeAccount = session.role === 'admin'
      ? await Admin.exists({ _id: session.accountId, active: true })
      : await Worker.exists({ _id: session.accountId, active: true });

    if (!activeAccount) {
      await Session.deleteOne({ _id: session._id });
      return fail(res, 401, 'AUTH_REQUIRED', 'Please sign in again.');
    }

    (req as AuthenticatedRequest).user = {
      role: session.role,
      id: String(session.accountId)
    };

    return next();
  } catch (error) {
    return next(error);
  }
}

export function requireAdmin(req: Request, res: Response, next: NextFunction) {
  if ((req as AuthenticatedRequest).user.role !== 'admin') {
    return fail(res, 403, 'ADMIN_ONLY', 'Administrator access is required.');
  }
  return next();
}
